### ISSUE TITLE
unknown type name 'float3'; did you mean 'float'?

### ISSUE THREAD

**Issue by danmonaghan** [ankou-7/ARSystem#1]
In MakeNavigationChoice/MakeNavigation/Render/shaderTypes.h at line 96-101 there are 6 floats for the realAnchorUniforms struct. I receive compile error for  `unknown type name 'float3'; did you mean 'float'?`
Is this an easy fix?

**Comment by ankou-7** [comment]
I've fixed that part. Thank you for letting me know.

**Comment by danmonaghan** [comment]
Fantastic, thanks, I haven't quite figured out how to use the entire app, have you got a YouTube video of the entire procedure? Would be keen to get in contact, great work!

**Comment by danmonaghan** [comment]
Oh, one question - are you perhaps on the M1 iPad? The performance on and iPhone 13 Pro Max is a bit jerky - I'll see if I can fix it? If the M1 iPad is that much faster then I'm very excited!

**Comment by ankou-7** [comment]
Sorry ... I don't have details on how to use it yet, but I'll add an explanation in the README. Please wait for a while.
Currently, I am running it on an iPad Pro (11") 3rd generation with M1.

**Comment by danmonaghan** [comment]
I suspected it was an M1 because you probably don't notice when the snapshots are taken that the session interrupts slightly. I've translated you app a few times to English - now I'll just try and keep my git's in sync and build an iPhone version for you that works in English.
